### ISSUE TITLE
Video quality resolutions: 540p instead of 720p

### ISSUE THREAD

**Issue by Ledigh** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#10]
Good morning !
 
Thanks for the programme:
Clear description and instructions ;)
 …
Even though “video quality” is set to high (720p) the program still downloads (did I say “randomly”) 540p quality videos files… for example using this following link:
[advanced-drum-recording-session-with-josh-freese](https://www.linkedin.com/learning/advanced-drum-recording-session-with-josh-freese?u=76279468) 
…results are a mix of 540p and 720p, though all 540p still have their corresponding 720p versions available; I can even download them from the “Internet Download Manager” button through its browser extension.

Any ideas about this issue ?
Thanks :)

**Comment by ahmedayman4a** [comment]
### Looks like this only happens with certain courses. After investigating the issue here is what I found:

The api that my app and most of the other downloaders is the same linkedin learning one. Maybe the website accesses a different api function but the one I use is `learning-api/detailedcourses`.
When making a get request for this api with 720p it sometimes returns a 540p video download url for some reason. This is the api's fault as it should return a 720p video as requested. Here is an example : 
- A request to `linkedin.com/learning-api/detailedCourses?courseSlug=advanced-drum-recording-session-with-josh-freese&resolution=_720&q=slugs&fields=selectedVideo&videoSlug=josh-freese-session-and-touring-drummer` returns a 540p video download url
- A request to `linkedin.com/learning-api/detailedCourses?courseSlug=advanced-drum-recording-session-with-josh-freese&resolution=_720&q=slugs&fields=selectedVideo&videoSlug=welcome` returns a 720p url

In both case `resolution=_720` is supplied but the api randomly responded with a 540p video in the first case.

There are 2 fixes I have in mind:

- Return to the selenium extraction which basically runs every video page in a browser and gets the correct download link. This would work but it is slow and sometimes causes random errors as seen with [LyndaCoursesDownloader v1.0 (Old version)](https://github.com/ahmedayman4a/LyndaCoursesDownloader/tree/v1.0.0).
- Try to reverse engineer the requests done by the linkedin learning mobile app and see if I can reproduce the requests with the app. I don't know if it is possible or if it is too complicated but if it is possible this would most likely require reprogramming the extractor.
