### ISSUE TITLE
Subtitles don't work

### ISSUE THREAD

**Issue by valenkovsky** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#3]
Are subtitles supported? It doesn't download it

**Comment by ahmedayman4a** [comment]
Subtitles should be downloaded. Which course didn't the subtitles get downloaded for?

**Comment by valenkovsky** [comment]
It doesn't download subtitles. I checked for several courses. For instance:
https://www.linkedin.com/learning/pandas-essential-training
I use Windows 10

**Comment by mahdisky** [comment]
hi bro
its very good, thnks,
but subtitle doesn't work,
not download subtitle
any course

**Comment by ahmedayman4a** [comment]
Ok, Expect a fix later today

**Comment by bestlong888** [comment]
The subtitle was working fine with 0.1 beta, but it's not working with the latest gui v1.0

**Comment by valenkovsky** [comment]
I see you've made a fix, can you make a release, please, or give instructions how to build it on Windows with Visual Studio

**Comment by ahmedayman4a** [comment]
Bug fixed with patch [v1.1](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/releases/tag/v1.1). If you already have the LinkedIn Learning Courses Downloader installed, you should be prompted for an update the next time you open the app. Start the update and the patch will be applied automatically.
