### ISSUE TITLE
[BUG] Error: Value cannot be null. Parameter name: source.

### ISSUE THREAD

**Issue by Shadabab** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#44]
**Describe the bug**
after inserting account Token and course URL from LinkedIn and pressing download, I get the following Error:
"Value cannot be Null Error -Parameter name: source "

**Operating System**
Windows 10

**Log File**
Upload the latest log file present at `%localappdata%\Linkedin-Learning-Courses-Downloader\app-1.1.0\logs` here.

<img width="960" alt="Downloader_Bug" src="https://user-images.githubusercontent.com/105660008/168630787-c5a79587-0da5-42e9-b9ac-a6f0ca68e104.png">

**Comment by ahmedayman4a** [comment]
You supplied a learning path url instead of a course url. Please get the links of the courses in this learning path and insert each one in its own line.
For example, 
Instead of entering this in the <Courses Url> field: 
https://www.linkedin.com/learning/paths/master-microsoft-power-bi-15399694
Enter this : 
https://www.linkedin.com/learning/power-bi-data-modeling-with-dax
https://www.linkedin.com/learning/power-bi-data-methods
https://www.linkedin.com/learning/power-bi-dataflows-essential-training
https://www.linkedin.com/learning/power-bi-top-skills-2019
https://www.linkedin.com/learning/power-bi-integrating-ai-and-machine-learning
https://www.linkedin.com/learning/advanced-microsoft-power-bi

**Comment by Shadabab** [comment]
Dear,

For some reason after trying to download, I am getting blank page on LinkedIn Learning page.

I can't see any content why? Was I blocked? 😔

I tried deleting cookies, signing out and in, nothing helped.

Could you help

**Comment by ahmedayman4a** [comment]
Refer to issue #37. It seems that after downloading a lot of stuff from LinkedIn at once, it bugs out. Try to download each course on its own next time with some time between them, or use the delay between course extractions option.

**Comment by Shadabab** [comment]
Hi,

Thank you for your reply
