### ISSUE TITLE
Bitdefender antivirus not allowing to install

### ISSUE THREAD

**Issue by HyperionWorld** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#5]
Antivirus detecting this software and showing as malware.
Is this software safe to install? Is this a malware?

**Comment by ahmedayman4a** [comment]
Bitdefender flags it but it is a false positive. This app is safe. It is open-source so you can see the code for yourself. You can also use decompiling software like [dotpeek](https://www.jetbrains.com/decompiler/). This decompiler will enable you to see the code that you run on your pc. If you want instrunctions on how to decompile the exe, tell me.

You can even run your own version of the code, here is how:

* Open visual studio and click on file then Clone Repository.
* For repository location type https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader.git.
* Click Clone.
* The code should be on your pc now. To edit the code, open the Linkedin-Learning-Courses-Downloader.sln file.
* In order to run LLCD.DownloaderGUI you need to have Update.exe file inside the bin folder.
* You can find this file under the LLCD.DownloaderGUI folder. Just copy and paste it in the bin folder.
